# Generated by Django 5.0 on 2024-01-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_telegramuser_location_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='location_km',
        ),
    ]
